### ISSUE TITLE
Figures background 

### ISSUE THREAD

**Issue by patricia-ternes** [ARCTraining/swd6_hpp#6]
Please consider adding 
```
facecolor='w'
```
to the figure definition so it also works well for people with jupyter lab dark mode.

**Comment by Sparrow0hawk** [comment]
@patricia-ternes can you recall where exactly we need to add this? Is it for every figure?

**Comment by jhodrien** [comment]
I don't think it'd cause problems for all figures, but it's only technically needed for figures with transparent backgrounds that seem to assume you've got a white background.

**Comment by patricia-ternes** [comment]
@Sparrow0hawk This issue is not mine. One participant put it in the chat during the first round.

But I looked at all notebooks in dark mode and I think the main problem are the images generated with `matplotlib` in the following locations:

https://github.com/ARCTraining/swd6_hpp/blob/17b5cc05c9edbb934aae1a64b0939df88b2a5d89/docs/00_overview.ipynb?short_path=bae5d51#L85-L118

https://github.com/ARCTraining/swd6_hpp/blob/17b5cc05c9edbb934aae1a64b0939df88b2a5d89/docs/00_overview.ipynb?short_path=bae5d51#L193-L256

**Comment by patricia-ternes** [comment]
Another problem is the `.svg` images (Dask related) in the parallelisation notebook:

https://github.com/ARCTraining/swd6_hpp/blob/17b5cc05c9edbb934aae1a64b0939df88b2a5d89/docs/05_parallelisation.ipynb
